
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE LPAREN MINUS NUMBER PLUS POINT RPAREN TIMESexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expressionexpression : LPAREN expression RPARENexpression : NUMBER POINT NUMBERexpression : NUMBER'
    
_lr_action_items = {'LPAREN':([0,2,4,5,6,7,],[2,2,2,2,2,2,]),'NUMBER':([0,2,4,5,6,7,9,],[3,3,3,3,3,3,15,]),'$end':([1,3,10,11,12,13,14,15,],[0,-7,-1,-2,-3,-4,-5,-6,]),'PLUS':([1,3,8,10,11,12,13,14,15,],[4,-7,4,4,4,4,4,-5,-6,]),'MINUS':([1,3,8,10,11,12,13,14,15,],[5,-7,5,5,5,5,5,-5,-6,]),'TIMES':([1,3,8,10,11,12,13,14,15,],[6,-7,6,6,6,6,6,-5,-6,]),'DIVIDE':([1,3,8,10,11,12,13,14,15,],[7,-7,7,7,7,7,7,-5,-6,]),'POINT':([3,],[9,]),'RPAREN':([3,8,10,11,12,13,14,15,],[-7,14,-1,-2,-3,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,4,5,6,7,],[1,8,10,11,12,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','appcalcula.py',49),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','appcalcula.py',50),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','appcalcula.py',51),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','appcalcula.py',52),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','appcalcula.py',56),
  ('expression -> NUMBER POINT NUMBER','expression',3,'p_expression_decimal','appcalcula.py',61),
  ('expression -> NUMBER','expression',1,'p_expression_number','appcalcula.py',66),
]
