
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ID LPAREN NUM RPAREN Reservada Reservada Reservada Reservada Reservada SEMIexpresion : ID LPAREN expresion RPAREN\n                 | NUM\n                 | Reservada\n    '
    
_lr_action_items = {'ID':([0,5,],[2,2,]),'NUM':([0,5,],[3,3,]),'Reservada':([0,5,],[4,4,]),'$end':([1,3,4,7,],[0,-2,-3,-1,]),'LPAREN':([2,],[5,]),'RPAREN':([3,4,6,7,],[-2,-3,7,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion':([0,5,],[1,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expresion","S'",1,None,None,None),
  ('expresion -> ID LPAREN expresion RPAREN','expresion',4,'p_expresion','app4.py',68),
  ('expresion -> NUM','expresion',1,'p_expresion','app4.py',69),
  ('expresion -> Reservada','expresion',1,'p_expresion','app4.py',70),
]
